import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import Providers from '@/components/Providers';

export const metadata: Metadata = {
  title: 'FlowMeet',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
